<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
 

 <div class="page-header">
<h2>
    <b> EDITAR COMPETIDOR</b>
    <?php echo $this->tag->linkTo(["competidor","class" => "back", "Voltar" ]) ?>

</h2>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "competidor/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNome">Nome</label>
        <?php echo $this->tag->textField(["nome", "size" => 30, "class" => "form-control", "id" => "fieldNome"]) ?>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <?php echo $this->tag->submitButton(["Salvar", "class" => "btn btn-primary btn-lg"]) ?>
</div>

<?php echo $this->tag->endForm(); ?>
