<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
<h2>
    <b>Resultado da busca:</b>
    <?php echo $this->tag->linkTo(["competidor","class" => "back", "Voltar" ]) ?>

</h2>
</div>

<?php echo $this->getContent(); ?>



        <?php foreach ($page->items as $competidor): ?>


        <div class="row">
        <div class="col-lg-5">
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object dp img-circle" src="../public/img/account.png" style="width: 100px;height:100px;">
            </a>
            <div class="media-body">
                <h4 class="media-heading"><b><?php echo $competidor->id ?></b> - <?php echo $competidor->nome ?></h4>
                <hr style="margin:8px auto">
                <?php echo $this->tag->linkTo(["competidor/edit/" . $competidor->id, "Editar", "class" => "btn btn-primary"]); ?>
                <?php echo $this->tag->linkTo(["competidor/delete/" . $competidor->id, "Deletar", "class" => "btn btn-primary"]); ?>
            </div>
        </div>
    </div>
    </div>
    <hr style="margin:8px auto">
        <?php endforeach; ?>



<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["competidor/search", "Primeira", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competidor/search?page=" . $page->before, "Anterior", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competidor/search?page=" . $page->next, "Próxima", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competidor/search?page=" . $page->last, "Última", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
