<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<script>
$(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>



<div class="jumbotron">
  <div class="container">
      <h2 class="header-title"><?php echo $competicao->nome;?></h2>
  </div>
</div>






<div class="row">



<section>
  <div class="tbl-header">
    <table cellpadding="0" cellspacing="0" border="0">
      <thead>
        <tr>
         <th>Posição (s)</th>
          <th>Competidor</th>
          <th>Tempo </th>
          <th>Tomada</th>
          <th>Tentativa</th>
        </tr>
      </thead>
    </table>
  </div>
  <div class="tbl-content">
    <table cellpadding="0" cellspacing="0" border="0">
      <tbody>

      <!-- foreach competidor -->
      <!-- <tr> -->
      <!--   <td>colocação</td> -->

      <?php foreach ($voltas as $volta): ?>
      <!--   <td>tempo<td> -->
      <!-- endforeach -->
      <!-- </tr> -->
      <!-- endforeach -->

      <?php foreach ($volta as $vol): ?>

        <tr>
          <td><span class="badge badge-primary">1º</span></td>
          <td><?php echo $vol->competidor->nome ?></td>
          <td><?php echo $vol->tempo ?> </td>
          <td><?php echo $vol->tomada ?></td>
          <td><?php echo $vol->tentativa ?></td>
          
        </tr>

        <?php endforeach;  ?>

        <?php endforeach;  ?>



      </tbody>
    </table>
  </div>
</section>
</div>

<?php echo $this->getContent() ?>
