<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>





<div class="jumbotron">
  <div class="container">
      <h2 class="header-title"><?php echo $competicao->nome;?></h2>
  </div>
</div>


<?php echo $this->getContent() ?>

<table class="table table-striped table-bordered table-list">

<thead>
<tr>
  <th>Posição (s)</th>
  <th>Competidor</th>
    <?php
        for ($i = 1; $i <= $competicao->tomadas; $i++) {
          echo "<th colspan='".$competicao->tentativas."'>Tomada " .$i."</th>";
        }
  ?>
</tr>
 </thead>
 <tbody>
      <!-- foreach competidor -->
      <!-- <tr> -->
      <!--   <td>colocação</td> -->
      <?php foreach ($voltas as $volta): ?>
      <!--   <td>tempo<td> -->
      <!-- endforeach -->
      <!-- </tr> -->
      <!-- endforeach -->
      <?php foreach ($volta as $vol): ?>
        <tr>
          <td><span class="badge badge-primary">1º</span></td>
          <td><?php echo $vol->competidor->nome ?></td>
          <?php $countVoltas = 0;?>
          <?php foreach ($volta as $compvolta): ?>
            <td><?php echo $compvolta->tempo ?> </td>
            <?php $countVoltas++; ?>
        <?php endforeach;  ?>
          <?php
                for ($i = $countVoltas ; $i< ($competicao->tomadas * $competicao->tentativas); $i++ ){
                    echo "<td> 0 </td>";
                }
          ?>
          <?php break;?>
        </tr>

        <?php endforeach;  ?>

        <?php endforeach;  ?>
</tbody>
</table>
