<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<script>
$(window).on("load resize ", function() {
  var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
  $('.tbl-header').css({'padding-right':scrollWidth});
}).resize();
</script>



<h2 class="indexTitle"><b><?php echo $competicao->nome;?></b></h2>

<div class="row">
<section>
  <div class="tbl-header">
    <table cellpadding="0" cellspacing="0" border="0">
      <thead>
        <tr>
          <th>Competidor</th>
          <th>1° Tempo (s)</th>
          <th>2º Tempo (s)</th>
          <th>3º Tempo (s)</th>
          <th>Posição (s)</th>
        </tr>
      </thead>
    </table>
  </div>
  <div class="tbl-content">
    <table cellpadding="0" cellspacing="0" border="0">
      <tbody>
        <tr>
          <td>AAC</td>
          <td>AUSTRALIAN COMPANY </td>
          <td>$1.38</td>
          <td>+2.01</td>
          <td><span class="badge badge-secondary">1º</span></td>
        </tr>
        <tr>
          <td>AAD</td>
          <td>AUSENCO</td>
          <td>$2.38</td>
          <td>-0.01</td>
          <td><span class="badge badge-secondary">2º</span></td>
        </tr>
        <tr>
          <td>AAX</td>
          <td>ADELAIDE</td>
          <td>$3.22</td>
          <td>+0.01</td>
          <td><span class="badge badge-secondary">3º</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</section>
</div>

<?php echo $this->getContent() ?>
