<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["competicaocompetidor", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit competicaocompetidor
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "competicaocompetidor/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdCompeticao" class="col-sm-2 control-label">Id Of Competicao</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_competicao", "type" => "number", "class" => "form-control", "id" => "fieldIdCompeticao"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdCompetidor" class="col-sm-2 control-label">Id Of Competidor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_competidor", "type" => "number", "class" => "form-control", "id" => "fieldIdCompetidor"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
