<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search competicaocompetidor
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["competicaocompetidor/new", "Create competicaocompetidor"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "competicaocompetidor/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdCompeticao" class="col-sm-2 control-label">Id Of Competicao</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_competicao", "type" => "number", "class" => "form-control", "id" => "fieldIdCompeticao"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdCompetidor" class="col-sm-2 control-label">Id Of Competidor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_competidor", "type" => "number", "class" => "form-control", "id" => "fieldIdCompetidor"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
