<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

 
<div class="jumbotron">


      <?php echo $this->tag->linkTo(["competicao","class" => "back", "Voltar" ]) ?>
 


  <div class="container">
    <h1><b><?php echo $competicao->nome ?></b></h1>
    <p><b>Data: </b><?php echo $competicao->data ?></p>
    <p><?php echo $competicao->descricao ?></p>
  </div>
  <div class="container">
    <h4> Iniciar </h4>
    <label class="switch">
      <input type="checkbox" name="competicaoativa">
      <span class="slider round"></span>
    </label>
  </div>

  <div class="container">
<h2> Competidores </h2>
    <ul class="list-group">
    <?php foreach ($competidores as $competidor): ?>
      <li class="list-group-item"><?php echo $competidor->nome ?></li>
    <?php endforeach;  ?>
    </ul>
</div>


<div class="media-body">
    <hr style="margin:8px auto">
    <?php echo $this->tag->linkTo(["competicao/edit/" . $competicao->id, "Editar", "class" => "btn btn-primary"]); ?>
    <?php echo $this->tag->linkTo(["competicao/delete/" . $competicao->id, "Deletar", "class" => "btn btn-primary"]); ?>
</div>

</div>







<?php echo $this->getContent(); ?>


