<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>


<script>

$( document ).ready(function() {
    $('#fieldData').mask('00/00/0000 00:00');
    

    //multiselect

    $('.searchable').multiSelect({
  selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Pesquisar'>",
  selectionHeader: "<h4 class='search-input'> Selecionados </h4>",
  afterInit: function(ms){
    var that = this,
        $selectableSearch = that.$selectableUl.prev(),
        $selectionSearch = that.$selectionUl.prev(),
        selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
        selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

    that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
    .on('keydown', function(e){
      if (e.which === 40){
        that.$selectableUl.focus();
        return false;
      }
    });

    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
    .on('keydown', function(e){
      if (e.which == 40){
        that.$selectionUl.focus();
        return false;
      }
    });
  },
  afterSelect: function(values){
    this.qs1.cache();
    this.qs2.cache();
       $("#competidores").val($("#competidores").val() + values +",");
  },
  afterDeselect: function(values){
    this.qs1.cache();
    this.qs2.cache();
    $("#competidores").val( $("#competidores").val().toString().replace(values+",", '') );
      //alert("Deselect value: "+values);
  }
});

});




</script>
<div class="col-lg-8 col-lg-offset-2">                      
<div class="page-header">
<h2>
    <b> EDITAR COMPETIÇÃO</b>
    <?php echo $this->tag->linkTo(["competicao","class" => "back", "Voltar" ]) ?>
 
</h2>
</div>

<?php echo $this->getContent(); ?>



<?php
    echo $this->tag->form(
        [
            "competicao/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<?php echo $this->tag->hiddenField("id") ?>
<div class="form-group">
    <label for="fieldNome">Nome</label>
        <?php echo $this->tag->textField(["nome", "size" => 30, "class" => "form-control", "id" => "fieldNome"]) ?>
</div>

<div class="form-group">
    <label for="fieldDescricao">Descrição</label>
        <?php echo $this->tag->TextArea(["descricao", "size" => 250, "class" => "form-control", "id" => "fieldDescricao"]) ?>
</div>



  <div class="form-group">
    <label for="fieldTomadas" class="col-2 col-form-label">Tomadas</label>
    <input class="form-control" type="number" value="<?php echo $competicao->tomadas;?>"  id="fieldTomadas" name="tomadas">
  </div>

  <div class="form-group">
    <label for="fieldTentativas" class="col-2 col-form-label">Tentativas</label>
    <input class="form-control" type="number" value="<?php echo $competicao->tentativas;?>" id="fieldTentativas" name="tentativas">
  </div>



<div class="form-group">
    <label for="fieldData" >Data e Horário</label>
    <?php echo $this->tag->textField(["data", "size" => 30, "class" => "form-control", "id" => "fieldData"]) ?>
</div>

<div class="form-group">
    <label for="my-select[]" >Competidores</label>
    <select multiple="multiple" id='custom-headers'  class="searchable">
        <?php foreach ($competidores as $competidor): ?>


          <?php 
          $verify = 0;
          foreach ($competicao->competicaocompetidor as $cc){
              if ($cc->id_competidor == $competidor->id){
                $verify = 1;
              }
          }
          
          if ($verify == 1){ ?>
          <option value="<?php echo $competidor->id ?>" selected><?php echo $competidor->nome ?></option>


          <?php  $comps = $comps.$competidor->id ."," ?>

          <?php }else{ ?>
            <option value="<?php echo $competidor->id ?>"><?php echo $competidor->nome ?></option>
          <?php } ?>

        



            



        <?php endforeach; ?>
    </select>
</div>

    <input type="hidden" value="<?php echo $comps; ?>" name="competidores" id="competidores">
    <input type="hidden" value="0" name="ativa" id="fieldAtiva">
<div class="form-group">
    <?php echo $this->tag->submitButton(["Salvar", "class" => "btn btn-primary btn-lg"]) ?>
</div>

  <?php echo $this->tag->endForm(); ?>
</div>



