<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="col-lg-8 col-lg-offset-2">                      
<h2 class="indexTitle"><b> COMPETIÇÃO</b></h2>
<div class="page-header">
<?php
    echo $this->tag->form(
        [
            "competicao/search",
            "autocomplete" => "on",
            "class" => "form-inline md-form mr-auto mb-4"
        ]
    );
?>

<div class="wrap">
   <div class="search">
      <input type="text" class="searchTerm" placeholder="Buscar" name="nome" id="fieldNome">

        <!-- sugestão de implementar busca por data -->
      <input type="hidden" class="searchTerm" placeholder="Buscar" name="data" id="fieldData">


      <button type="submit" class="searchButton">
      <i class="fa fa-search" aria-hidden="true"></i>    
       </button>
   </div>
</div>
<!-- fieldData -->
   <?php echo $this->getContent() ?>
<?php echo $this->tag->endForm(); ?>

</div>
    
    <p>
         <?php echo $this->tag->linkTo(["competicao/new","class" => "btn btn-primary btn-lg", "+"]) ?>
    </p>
   



</div>

</div>








