<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<script>
 $('#fieldData').mask('00/00/0000 00:00');
</script>

<div class="page-header">
<h2>
    <b> CRIAR COMPETIÇÃO</b>
    <a href="/cronometro/competicao" class="back"> Voltar </a>
</h2>
</div>

<?php echo $this->getContent(); ?>



<?php
    echo $this->tag->form(
        [
            "competicao/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNome">Nome</label>
        <?php echo $this->tag->textField(["nome", "size" => 30, "class" => "form-control", "id" => "fieldNome"]) ?>
</div>


<div class="form-group">
    <label for="fieldDescricao">Descrição</label>
        <?php echo $this->tag->TextArea(["descricao", "size" => 250, "class" => "form-control", "id" => "fieldDescricao"]) ?>
</div>

<div class="form-group">
    <label for="fieldData" >Data e Horário</label>
    <?php echo $this->tag->textField(["data", "size" => 30, "class" => "form-control", "id" => "fieldData"]) ?>
</div>

<div class="form-group">
    <?php echo $this->tag->submitButton(["Criar", "class" => "btn btn-primary btn-lg"]) ?>
</div>

  <?php echo $this->tag->endForm(); ?>






