<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<script>

$( document ).ready(function() {
    $('#fieldData').mask('00/00/0000 00:00');
    $('#my-select').multiSelect();
});


</script>

<div class="page-header">
<h2>
    <b> CRIAR COMPETIÇÃO</b>
    <?php echo $this->tag->linkTo(["competicao","class" => "back", "Voltar" ]) ?>

</h2>
</div>

<?php echo $this->getContent(); ?>



<?php
    echo $this->tag->form(
        [
            "competicao/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNome">Nome</label>
        <?php echo $this->tag->textField(["nome", "size" => 30, "class" => "form-control", "id" => "fieldNome"]) ?>
</div>


<div class="form-group">
    <label for="fieldDescricao">Descrição</label>
        <?php echo $this->tag->TextArea(["descricao", "size" => 250, "class" => "form-control", "id" => "fieldDescricao"]) ?>
</div>

<div class="form-group">
    <label for="fieldData" >Data e Horário</label>
    <?php echo $this->tag->textField(["data", "size" => 30, "class" => "form-control", "id" => "fieldData"]) ?>
</div>

<div class="form-group">
    <label for="my-select[]" >Competidores</label>
    <select multiple="multiple" id="my-select" name="my-select[]">
        <option value='elem_1'>elem 1</option>
        <option value='elem_2'>elem 2</option>
        <option value='elem_3'>elem 3</option>
        <option value='elem_4'>elem 4</option>
        <option value='elem_100'>elem 100</option>
    </select>
</div>
<div class="form-group">
    <?php echo $this->tag->submitButton(["Criar", "class" => "btn btn-primary btn-lg"]) ?>
</div>

  <?php echo $this->tag->endForm(); ?>






