<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>



<div class="row">

        <?php foreach ($page->items as $competicao): ?>
            <div class="card">
            <h3 class="card-header"><?php echo $competicao->nome ?></h3>
            <div class="card-body">
                <h5 class="card-title"> <?php echo $competicao->data ?></h5>
                <p class="card-text"> <?php echo $competicao->descricao ?></p>
                <a href="#" class="btn btn-primary">Ver mais</a>
                </div>
            </div>
        <?php endforeach; ?>

</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["competicao/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["competicao/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["competicao/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>


