<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>

<style>
.demo-card-square.mdl-card {
  width: 320px;
  height: 320px;
  margin-left: 3%;
  margin-top: 3%;
}
.demo-card-square > .mdl-card__title {
  color: #fff;
  background: url('img\trophy.png') bottom right 15% no-repeat #A61D3E;
}
</style>





<div class="row">

        <?php foreach ($page->items as $competicao): ?>


        <div class="demo-card-square mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
            <h2 class="mdl-card__title-text"><?php echo $competicao->nome ?></h2>
            <img src="../public/img/trophy.png">
        </div>
        <div class="mdl-card__supporting-text">
        <?php echo $competicao->data ?>
        </div>
        <div class="mdl-card__actions mdl-card--border">
           <?php //echo $this->tag->linkTo(["competicao/edit/" . $competicao->id, "Edit"]); ?>
            <?php //echo $this->tag->linkTo(["competicao/delete/" . $competicao->id, "Delete"]); ?>
         <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
            Mais
            </a>
        </div>
        </div>
        <?php endforeach; ?>

</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["competicao/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["competicao/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["competicao/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>


