<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
<h2>
    <b>Resultado da busca:</b>
    <?php echo $this->tag->linkTo(["competicao","class" => "back", "Voltar" ]) ?>

</h2>
</div>
<?php echo $this->getContent(); ?>



<div class="row">

        <?php foreach ($page->items as $competicao): ?>
        <div class="col-sm-4 col-md-4 col-lg-6">
            <div class="thumbnail">
            <div class="caption">
                <h3><?php echo $competicao->nome ?></h3>
                <h5><b>Data:</b> <?php echo $competicao->data ?></h5>
                <p><?php echo $competicao->descricao ?></p>
                <p><a href="#" class="btn btn-primary" role="button">Ver mais</a></p>
            </div>
            </div>
        </div>
        <?php endforeach; ?>

</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["competicao/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["competicao/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>



