<!DOCTYPE html>
<html ng-app>
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Cronômetro</title>
        <link rel="shortcut icon" href="favicon.ico">
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="https://use.fontawesome.com/e9c09e0601.js"></script>
        <?php 
              $this->assets->addCss('public/css/multi-select.css'); 
              $this->assets->addCss('public/css/styles.css');
              $this->assets->addJs('public/js/script.js');
              $this->assets->addJs('public/js/jquery.mask.min.js');
              $this->assets->addJs('public/js/jquery.multi-select.js');
              $this->assets->addJs('public/js/jquery.quicksearch.js');
              $this->assets->outputCss(); 
              $this->assets->outputJs();
         ?>
    </head>
    <body>


  
    <div id="wrapper">
        <div class="overlay"></div>
        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li class="sidebar-brand">
                <b class="logo">
                <?php echo Phalcon\Tag::linkTo(
                        [
                            "index",
                            "Cronômetro IoT"
                        ]
                    );?>
                </b>
                </li>
                <li>
                    <?php echo Phalcon\Tag::linkTo(
                        [
                            "competicao",
                            "Competições"
                        ]
                    );?>
                </li>
                <li>
                <li>
                    <?php echo Phalcon\Tag::linkTo(
                        [
                            "competidor",
                            "Competidores"
                        ]
                    );?>
                </li>
                </li>
            </ul> 
        </nav>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                <span class="hamb-top"></span>
    			<span class="hamb-middle"></span>
				<span class="hamb-bottom"></span>
            </button>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">                      
                        <?php echo $this->getContent(); ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>
</html>
