<!DOCTYPE html>
<html ng-app>
    <head> 
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Cronômetro</title>
        <link rel="shortcut icon" type="image/x-icon" href="/cronometro/public/img/favicon.ico">
        <?php 

              $this->assets->addCss('/public/css/bootstrap.min.css');
              $this->assets->addCss('/public/css/font-awesome/css/font-awesome.min.css');
              $this->assets->addCss('/public/css/multi-select.css'); 
              $this->assets->addCss('/public/css/styles.css');
             
              $this->assets->addJs('public/js/jquery-1.11.1.min.js');
              $this->assets->addJs('public/js/bootstrap.min.js');
              $this->assets->addJs('public/js/script.js');
              $this->assets->addJs('public/js/jquery.mask.min.js');
              $this->assets->addJs('public/js/jquery.multi-select.js');
              $this->assets->addJs('public/js/jquery.quicksearch.js');

              $this->assets->outputJs();
              $this->assets->outputCss(); 
             
         ?>
    </head>
    <body>


  
    <div id="wrapper">
        <div class="overlay"></div>
        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li class="sidebar-brand">
                <?php echo Phalcon\Tag::linkTo(
                        [
                            "index",
                            "","class" => "fa fa-clock-o fa-2x"
                        ]
                    );?>
                </li>
                <li style="margin-top:20px;">
                    <?php echo Phalcon\Tag::linkTo(
                        [
                            "competicao",
                            "Competições"
                        ]
                    );?>
                </li>
                <li>
                <li>
                    <?php echo Phalcon\Tag::linkTo(
                        [
                            "competidor",
                            "Competidores"
                        ]
                    );?>
                </li>
                </li>
            </ul> 


        </nav>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                <span class="hamb-top"></span>
    			<span class="hamb-middle"></span>
				<span class="hamb-bottom"></span>
            </button>
            <div class="container">
                <div class="row">
                        <?php echo $this->getContent(); ?>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>
</html>
